SELECT 
       AC.NUMSERIEFAC
	  ,AC.NUMFAC
	  ,AC.NUMSERIE
	  ,AC.NUMALBARAN
	  ,C.CODCLIENTE
      ,C.NOMBRECLIENTE
	  ,C.NOMBRECOMERCIAL
      ,CAST(FECHA AS DATE) AS FECHA 
	  ,AL.CODARTICULO
	  ,AL.DESCRIPCION

	  ,CL.TIPOS_DE_CONSUMO
	  ,(CASE WHEN CL.CLIENTE_BOX IS NULL AND CL.TIPOS_DE_CONSUMO = 'CLIENTE_BOX' THEN 'OTROS' ELSE CL.CLIENTE_BOX END) CLIENTE_BOX
	  ,AL.UNIDADESTOTAL
      ,AL.TOTAL
  FROM ALBVENTACAB  AC INNER JOIN ALBVENTALIN AL ON AL.NUMSERIE=AC.NUMSERIE AND AL.NUMALBARAN=AC.NUMALBARAN
                       inner join CLIENTES C ON C.CODCLIENTE=AC.CODCLIENTE
					   inner join CLIENTESCAMPOSLIBRES CL ON CL.CODCLIENTE=C.CODCLIENTE
					    

  WHERE AL.NUMSERIE <> 'AMVN' AND CODARTICULO <> '-1'
 --AND CL.TIPOS_DE_CONSUMO LIKE '%BOX%'
  ORDER BY NUMFAC DESC 