SELECT 
       AC.NUMSERIEFAC
	  ,AC.NUMFAC
	  ,AC.NUMSERIE
	  ,AC.NUMALBARAN
	  ,C.CODCLIENTE
      ,C.NOMBRECLIENTE
	  ,C.NOMBRECOMERCIAL
      ,CAST(FECHA AS DATE) AS FECHA 
	  ,AL.CODARTICULO
	  ,AL.DESCRIPCION
	  ,AL.UNIDADESTOTAL
      ,AL.TOTAL
  FROM ALBVENTACAB  AC INNER JOIN ALBVENTALIN AL ON AL.NUMSERIE=AC.NUMSERIE AND AL.NUMALBARAN=AC.NUMALBARAN
                       inner join CLIENTES C ON C.CODCLIENTE=AC.CODCLIENTE

  WHERE AL.NUMSERIE <> 'AMVN'
 
  ORDER BY NUMFAC DESC 